import { getSession } from '@setlister/auth/server';
import '@setlister/utils/global.css';
import Providers from './Providers';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <Providers session={session}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
